### ISSUE TITLE
[bug] Quick Change not working

### ISSUE THREAD

**Issue by Altoholic** [RagedUnicorn/wow-vanilla-gearmenu#15] opened 2019-01-26 21:42 UTC
I tried it with spider belt (with no cooldown) and skull of impending doom (with a cooldown, just to try it). I can create rules, but they never do anything.

**Comment by RagedUnicorn** [comment] 2019-02-13 22:05
Hi do you have any more details for me to reproduce. When I tried a basic situation it worked without a problem but quick change definitely has its limititations such as when you are stunned or have a similar effect on you.

When you created a rule what time did you set? What are the exact items you used for the rule? From what item did you want to switch to what other item.

Regards,
RagedUnicorn

**Comment by Altoholic** [comment] 2019-02-15 10:12
I tried again today, and all is working fine. No idea what was the problem is the first place (but as i have updated some addons, maybe it was a conflict).

**Comment by Altoholic** [comment] 2019-02-15 10:27
I talked too fast.
A rule with no timer will work.
A rule with a timer will maybe work, if i let the buff given by the item untouched.

For Skull of Impending Doom i use this macro (with supermacro addon):

```
/script UseItemByName ("Skull of Impending Doom")
/Unbuff Flee
```

The point is to no let the buff do the full self damage, and instead get rid of it when it is not needed anymore.
If i use the macro, QuickChange will not do anything.
If i let the debuff run free to the full duration (10 sec), QuickChange will work.
I'm using a 10 sec duration for QuickChange.

**Comment by RagedUnicorn** [comment] 2019-04-28 14:12
Hi,

Going to close this because I wasn't able to reproduce this. Feel free to create a new issue if you have more details on how to reporduce the issue.

Cheers,
RagedUnicorn

**Closed by RagedUnicorn** 2019-04-28 14:12 UTC
